-- Run this entire file in Supabase SQL Editor.
-- Also upgrades the earlier public-demo tasks table without deleting its rows.
begin;
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  course text,
  due_date date,
  priority text not null default 'Medium' check (priority in ('Low','Medium','High')),
  notes text,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.tasks add column if not exists user_id uuid default auth.uid() references auth.users(id) on delete cascade;
alter table public.tasks enable row level security;
drop policy if exists "Public can read tasks" on public.tasks;
drop policy if exists "Public can insert tasks" on public.tasks;
drop policy if exists "Public can update tasks" on public.tasks;
drop policy if exists "Public can delete tasks" on public.tasks;
drop policy if exists "Users manage own tasks" on public.tasks;
create policy "Users manage own tasks" on public.tasks
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
revoke all on public.tasks from anon;
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.tasks to authenticated;
grant usage, select on sequence public.tasks_id_seq to authenticated;
create index if not exists tasks_user_id_idx on public.tasks(user_id);
commit;
-- Earlier public demo rows have no owner and are hidden by the new policy.
